# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
dist: xenial
cache: packages
latex: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev

r:
  - release
  - devel
  - oldrel
